- name: variables to print
  hosts: web
  vars:
    COURSE: "DEVOPS WITH AWS"
    DURATION: "120"
    TRAINER: "VENU"
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "i am learning {{COURSE}}, duration is {{DURATION}}, trainer is {{TRAINER}}"

  - name: print the information agian
    vars:
      COURSE: "ANSIBLE"
    ansible.builtin.debug:
      msg: "i am learning {{COURSE}}, duration is {{DURATION}}, trainer is {{TRAINER}}"

  - name: print the information again and again
    ansible.builtin.debug:
      msg: "i am learning {{COURSE}}, duration is {{DURATION}}, trainer is {{TRAINER}}"