- name: print the variables
  hosts: web
  vars_file:
  - vars.yaml
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "Hi, i am learning {{COURSE}},Duration is: {{DURATION}},Trainer: {{TRAINER}} "