- name: create ec2 instance and r53 records
  hosts: local
  connection: local
  vars:
    subnet_id: subnet-097f6bf272b7a83ca
    sg_id: "sg-0c1a4484e8e5bd2c3"
    ami_id: "ami-09c813fb71547fc4f"
    instances:
    - mysql
    - backend
    - frontend
    zone: devopsaws56.online
  tasks:
  - name: create the ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: "t3.micro"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
    loop: "{{ instances }}"
    register: ec2_instances
    
  - name: print the output
    ansible.builtin.debug:
      msg: "{{ ec2_instances }}"
  
 
